[package]

name = "libusb1-sys"
version = "0.6.4"
authors = ["David Cuddeback <david.cuddeback@gmail.com>",
            "Ilya Averyanov <a1ien.n3t@gmail.com>"]
description = "FFI bindings for libusb."
license = "MIT"
homepage = "https://github.com/a1ien/rusb"
repository = "https://github.com/a1ien/rusb.git"
readme = "README.md"
keywords = ["usb", "libusb", "hardware", "bindings"]
edition = "2018"
links = "usb-1.0" # Required for metadata passing to work

include = [
    "/exaples",
    "/libusb/libusb",
    "/libusb/msvc",
    "/src/*",
    "/tests",
    "build.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "CHANGELOG.md",
    "COPYING",
    "AUTHORS",
]

build = "build.rs"

[badges]
travis-ci = { repository = "a1ien/libusb1-sys" }

[features]
vendored = []

[dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.build-dependencies]
vcpkg = "0.2"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"
